# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "tron"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Delon Newman"]
  s.date = "2014-08-23"
  s.description = "Rack based web application and middleware for user user management"
  s.email = "drnewman@phrei.org"
  s.executables = ["tron-generate-secret"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitmodules",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "Vagrantfile",
    "bin/tron-generate-secret",
    "config.ru",
    "config/.keep",
    "config/database.sample.yml",
    "db/migrations/001_initial_migration.rb",
    "db/migrations/002_add_activated_to_users.rb",
    "db/migrations/003_add_application_id_to_permissions.rb",
    "db/migrations/004_add_activation_key_to_users.rb",
    "db/migrations/005_add_crypted_access_code_to_users.rb",
    "db/schema.rb",
    "db/seed.rb",
    "example/config.ru",
    "example/doorway.rb",
    "lib/sinatra/tron.rb",
    "lib/tron.rb",
    "lib/tron/admin/app.rb",
    "lib/tron/admin/views/activation.haml",
    "lib/tron/admin/views/activation_error.haml",
    "lib/tron/admin/views/activation_success.haml",
    "lib/tron/admin/views/home.haml",
    "lib/tron/admin/views/layout.haml",
    "lib/tron/admin/views/new_user.haml",
    "lib/tron/admin/views/simple_layout.haml",
    "lib/tron/admin/views/user_activation.haml",
    "lib/tron/admin/views/user_list.haml",
    "lib/tron/admin/views/user_view.haml",
    "lib/tron/db.rb",
    "lib/tron/middleware/app.rb",
    "lib/tron/middleware/helpers.rb",
    "lib/tron/middleware/views/layout.haml",
    "lib/tron/middleware/views/login.haml",
    "lib/tron/model.rb",
    "lib/tron/model/application.rb",
    "lib/tron/model/permission.rb",
    "lib/tron/model/user.rb",
    "lib/tron/model/user_permission.rb",
    "lib/tron/session.rb",
    "lib/tron/utils.rb",
    "scripts/bootstrap",
    "scripts/setupdbs",
    "spec/admin_spec.rb",
    "spec/helper.rb",
    "spec/middleware_spec.rb",
    "spec/user_spec.rb",
    "tron.gemspec"
  ]
  s.homepage = "http://phrei.org"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Rack based web application and middleware for user user management"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<vista-hui_data>, ["~> 0.1.0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra-contrib>, [">= 0"])
      s.add_runtime_dependency(%q<warden>, [">= 0"])
      s.add_runtime_dependency(%q<sequel>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra-sequel>, [">= 0"])
      s.add_runtime_dependency(%q<pg>, [">= 0"])
      s.add_runtime_dependency(%q<pony>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<sass>, [">= 0"])
      s.add_runtime_dependency(%q<coffee-script>, [">= 0"])
      s.add_runtime_dependency(%q<rack-flash3>, [">= 0"])
      s.add_runtime_dependency(%q<bcrypt>, [">= 0"])
      s.add_runtime_dependency(%q<monad-maybe>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra-static-assets>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<sprockets>, [">= 0"])
      s.add_development_dependency(%q<shotgun>, [">= 0"])
    else
      s.add_dependency(%q<vista-hui_data>, ["~> 0.1.0"])
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<sinatra-contrib>, [">= 0"])
      s.add_dependency(%q<warden>, [">= 0"])
      s.add_dependency(%q<sequel>, [">= 0"])
      s.add_dependency(%q<sinatra-sequel>, [">= 0"])
      s.add_dependency(%q<pg>, [">= 0"])
      s.add_dependency(%q<pony>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<sass>, [">= 0"])
      s.add_dependency(%q<coffee-script>, [">= 0"])
      s.add_dependency(%q<rack-flash3>, [">= 0"])
      s.add_dependency(%q<bcrypt>, [">= 0"])
      s.add_dependency(%q<monad-maybe>, [">= 0"])
      s.add_dependency(%q<sinatra-static-assets>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<sprockets>, [">= 0"])
      s.add_dependency(%q<shotgun>, [">= 0"])
    end
  else
    s.add_dependency(%q<vista-hui_data>, ["~> 0.1.0"])
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<sinatra-contrib>, [">= 0"])
    s.add_dependency(%q<warden>, [">= 0"])
    s.add_dependency(%q<sequel>, [">= 0"])
    s.add_dependency(%q<sinatra-sequel>, [">= 0"])
    s.add_dependency(%q<pg>, [">= 0"])
    s.add_dependency(%q<pony>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<sass>, [">= 0"])
    s.add_dependency(%q<coffee-script>, [">= 0"])
    s.add_dependency(%q<rack-flash3>, [">= 0"])
    s.add_dependency(%q<bcrypt>, [">= 0"])
    s.add_dependency(%q<monad-maybe>, [">= 0"])
    s.add_dependency(%q<sinatra-static-assets>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<sprockets>, [">= 0"])
    s.add_dependency(%q<shotgun>, [">= 0"])
  end
end

